name: 'Tests: node.js >= 10'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '>= 10'
      type: minors
      command: npm run test
